import Head from 'next/head'
import Body from '../components/Body/Body'
import Services from './../components/Services/Services'

export default function Service() {
    return (
      <>
        <Head>
          <title>Services</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
        </Head>
          <Body>
          <Services />
          </Body>
          
        
      </>
    )
  }